name: Branch Naming Convention Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          PATTERN="^(feature|bugfix|hotfix|chore|experiment|dev)/[a-zA-Z0-9_-]+(/[a-zA-Z0-9_-]+)?$|^dev$"
          
          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "❌ Branch name '$BRANCH_NAME' does not follow the convention:"
            echo "   <type>/<name>/<issue> or <type>/<name> or dev"
            echo "   where <type> is one of: feature, bugfix, hotfix, chore, experiment, dev"
            exit 1
          else
            echo "✅ Branch name follows convention: $BRANCH_NAME"
          fi